name: log commits
on:
  push:
    branches: [main]
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      COMMIT_LOG_API: ${{ secrets.COMMIT_LOG_API }}
      COMMITS: ${{ toJSON(github.event.commits) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is important so git fetches all history.. the actions/checkout by default fetches all history as one commit which throws off stats
      - uses: actions/setup-python@v3
        with:
          python-version: "^3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitcommitlogger
      - name: Logging
        run: |
          # git log --stat -n $(echo $COMMITS | jq '. | length' ) # another way to try to get just the latest commits
          echo $COMMITS > commits.json
          gitcommitlogger -i commits.json -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v
